fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "vcsrepo": "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    "tp": "https://github.com/example42/puppet-tp"
    "tinydata": "https://github.com/example42/tinydata"
  symlinks:
    "psick": "#{source_dir}"
